version: '3'

services:

  mysql:
    container_name: Album_mysql
    image: mysql:8.0.31
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=album
      - MYSQL_USER=album
      - MYSQL_PASSWORD=pass
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  redis:
    container_name: Album_redisdb
    image: redis:7.0.5
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./.docker/redis-data:/data

  minio:
    container_name: Album_minio
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: album
      MINIO_ROOT_PASSWORD: albumsecret
    command: server --console-address ":9001" /data

volumes:
  minio_storage:
