  version: '3'

  services:

    postgres:
      container_name: Album_postgresdb
      image: postgres:15.0
      restart: always
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        - POSTGRES_DB=album
        - POSTGRES_USER=album
        - POSTGRES_PASSWORD=pass
      volumes:
        - ./.docker/postgresql-data:/var/lib/postgresql/data

    redis:
      container_name: Album_redisdb
      image: redis:7.0.5
      restart: always
      ports:
        - "127.0.0.1:6379:6379"
      volumes:
        - ./.docker/redis-data:/data
